package facebook.dao;
// Generated 26 Aug, 2016 10:28:34 AM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;

import facebook.jsonview.Views;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "post")
public class Comment implements java.io.Serializable {
	@JsonView(Views.Public.class)
	private Integer CId;
	@JsonView(Views.Public.class)
	private User user;
	@JsonView(Views.Public.class)
	private int postId;
	@JsonView(Views.Public.class)
	private String CText;
	@JsonView(Views.Public.class)
	private String CTime;
	@JsonView(Views.Public.class)
	private String UTime;

	public Comment() {
	}

	public Comment(User user, int postId, String CText, String CTime, String UTime) {
		this.user = user;
		this.postId = postId;
		this.CText = CText;
		this.CTime = CTime;
		this.UTime = UTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "C_ID", unique = true, nullable = false)
	public Integer getCId() {
		return this.CId;
	}

	public void setCId(Integer CId) {
		this.CId = CId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "U_ID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "POST_ID", nullable = false)
	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	@Column(name = "C_TEXT", nullable = false, length = 65535)
	public String getCText() {
		return this.CText;
	}

	public void setCText(String CText) {
		this.CText = CText;
	}

	@Column(name = "C_TIME", nullable = false)
	public String getCTime() {
		return this.CTime;
	}

	public void setCTime(String CTime) {
		this.CTime = CTime;
	}

	@Column(name = "U_TIME", nullable = false)
	public String getUTime() {
		return this.UTime;
	}

	public void setUTime(String UTime) {
		this.UTime = UTime;
	}

}
