package facebook.dao;
// Generated 26 Aug, 2016 10:28:34 AM by Hibernate Tools 5.1.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name = "post", catalog = "post")
public class Post implements java.io.Serializable {

	private Integer postid;
	private int uid;
	private String ptext;
	private int likes;
	private String ctime;
	private String utime;

	public Post() {
	}

	public Post(int uid, String ptext, int likes, String ctime, String utime) {
		this.uid = uid;
		this.ptext = ptext;
		this.likes = likes;
		this.ctime = ctime;
		this.utime = utime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "postid", unique = true, nullable = false)
	public Integer getPostid() {
		return this.postid;
	}

	public void setPostid(Integer postid) {
		this.postid = postid;
	}

	@Column(name = "uid", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "ptext", nullable = false, length = 65535)
	public String getPtext() {
		return this.ptext;
	}

	public void setPtext(String ptext) {
		this.ptext = ptext;
	}

	@Column(name = "likes", nullable = false)
	public int getLikes() {
		return this.likes;
	}

	public void setLikes(int likes) {
		this.likes = likes;
	}

	@Column(name = "ctime", nullable = false)
	public String getCtime() {
		return this.ctime;
	}

	public void setCtime(String ctime) {
		this.ctime = ctime;
	}

	@Column(name = "utime", nullable = false)
	public String getUtime() {
		return this.utime;
	}

	public void setUtime(String utime) {
		this.utime = utime;
	}

}
