package facebook.dao;
// Generated 26 Aug, 2016 10:28:34 AM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonView;

import facebook.jsonview.Views;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "post")
public class User implements java.io.Serializable {
	@JsonView(Views.Public.class)
	private Integer id;
	private String email;
	private String password;
	private String firstname;
	private String image;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set<Comment> comments_1 = new HashSet<Comment>(0);
	private Set<Comment> comments_2 = new HashSet<Comment>(0);

	public User() {
	}

	public User(String email, String password, String firstname, String image) {
		this.email = email;
		this.password = password;
		this.firstname = firstname;
		this.image = image;
	}

	public User(String email, String password, String firstname, String image, Set<Comment> comments,
			Set<Comment> comments_1, Set<Comment> comments_2) {
		this.email = email;
		this.password = password;
		this.firstname = firstname;
		this.image = image;
		this.comments = comments;
		this.comments_1 = comments_1;
		this.comments_2 = comments_2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstname", nullable = false)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "image", nullable = false)
	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Comment> getComments_1() {
		return this.comments_1;
	}

	public void setComments_1(Set<Comment> comments_1) {
		this.comments_1 = comments_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Comment> getComments_2() {
		return this.comments_2;
	}

	public void setComments_2(Set<Comment> comments_2) {
		this.comments_2 = comments_2;
	}

}
